# Generated by Django 5.1.7 on 2025-03-24 05:33

import appointments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('appointment_type', models.CharField(choices=[('CONS', 'Consultation'), ('CHKP', 'Checkup'), ('FOLW', 'Follow-up'), ('EMRG', 'Emergency')], default='CONS', max_length=4)),
                ('date_time', models.DateTimeField(validators=[appointments.models.validate_future_date])),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date_time'],
            },
        ),
    ]
