# Generated by Django 5.1.7 on 2025-03-24 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'managed': False, 'ordering': ['date_time']},
        ),
    ]
