name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
          pip install awsebcli

      - name: Run tests
        run: |
          pytest

      - name: Generate deployment package
        run: |
          zip -r deploy.zip . -x "*.git*" "*.github*" "venv/*" "*.pytest_cache*" "*.env"

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: appointment-scheduler
          environment_name: appointment-scheduler-env
          version_label: "appointment-scheduler-${{ github.sha }}"
          region: eu-west-1
          deployment_package: deploy.zip